name: Clang Format Checker
on:
  push:
  workflow_dispatch:

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: RafikFarhad/clang-format-github-action@v2.1.0
        with:
          sources: "src/*.c,src/*.h,src/noobprobe/*.c,src/noobprobe/*.h"